### ISSUE TITLE
Print empty lines in file

### ISSUE THREAD

**Issue by dha** [dnmfarrell/Perl6-One-Liners#14]
perl6 -e 'lines.grep(/\s/).elems.say' example.txt

does not work for this. It matches any line with a space in it.

perl6 -e 'lines.grep(/^\s$).elems.say' would work, also perl6 -e 'lines.grep({ $_ !~~ /\S/}).elems.say'

**Comment by dnmfarrell** [comment]
Doh, thanks for reporting this! I've fixed it with:

    perl6 -e 'lines.grep(/^\s*$).elems.say

**Comment by dha** [comment]
You're missing a closing slash, there... But it looks like you included it in the actual text. \o/ :-)
