### ISSUE TITLE
.map({ [~] @$_ }) is the same as >>.join

### ISSUE THREAD

**Issue by timo** [dnmfarrell/Perl6-One-Liners#20]
much easier to type and remember, IMO.

**Comment by dnmfarrell** [comment]
Are you sure? I get different results:

    $ perl6 -e 'my $n=2; say "banana".comb.rotor($n,$n-1).map({[~] @$_})'
    (ba n an a)
    $ perl6 -e 'my $n=2; say "banana".comb.rotor($n,$n-1).join'                                                    
    b ana na

**Comment by will-crawford** [comment]
$ perl6 -e 'my $n=2; say "banana".comb.rotor($n,$n-1)>>.join'
    (ba n an a)

**Comment by dnmfarrell** [comment]
D'oh, thanks! fixed in commit `a9884c369fc31cf70d47fcf8169e47d758bed65b`
